build.gradle, src/main/java/com/skyhorsemanpower/BE_AuctionPost/BeAuctionPostApplication.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/AuctionPostService.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/common/BaseCreateAndEndTimeEntity.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/common/CustomException.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/common/ExceptionResponse.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/common/GlobalExceptionHandler.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/common/SuccessResponse.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/config/QuartzConfig.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/config/SwaggerConfig.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/dto/CreateAuctionPostDto.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/vo/CreateAuctionPostRequestVo.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/domain/AuctionImages.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/domain/cqrs/command/CommandAuctionPost.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/domain/cqrs/read/ReadAuctionPost.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/presentation/AuthorizationAuctionController.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/quartz/EndAuctionPost.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/AuctionImagesRepository.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/cqrs/command/CommandAuctionPostRepository.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/cqrs/read/ReadAuctionPostRepository.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/status/AuctionStateEnum.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/status/ResponseStatus.java, src/main/resources/application.yml, src/test/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImplTest.java
#1 
경매글 작성 API 구현하였습니다.
첫 셋팅이라 추가된 파일들이 많으나 컨트롤러, 서비스 구현체만 보시면 될 듯 합니다.
=> Feature/#1 경매글 생성 기능 구현

src/main/java/com/skyhorsemanpower/BE_AuctionPost/BeAuctionPostApplication.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/common/BaseCreateAndEndTimeEntity.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/config/JpaConfig.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/dto/CreateAuctionPostDto.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/vo/CreateAuctionPostRequestVo.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/domain/cqrs/command/CommandAuctionPost.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/domain/cqrs/read/ReadAuctionPost.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/presentation/AuctionPostController.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/status/AuctionStateEnum.java
변경된 기획에 맞게 경매글 생성을 수정했습니다.
경매글 필드
`경매 식별자(AuctionUuid)`, `작성자 식별자(adminUuid)`, `참여자 식별자(influencerUuid)`, `제목(title)`, `내용(content)`, `행사 장소(eventPlace)`, `행사 시작 시간(eventStartTime)`, `행사 마감 시간(eventCloseTime)`,` 경매 시작 시간(AuctionStartTime)`, `시작가(StartPrice)`, `단위가(IncrementUnit)`, `경매 상태(state)`, `작성시간(createdAt)`, `수정시간(updatedAt)`
수정시간은 경매 상태 갱신 시간을 알려주기 위해서 명시했습니다.
경매 상태 다음처럼 만들었습니다.
```    
// 경매 진행 전
BEFORE_AUCTION,
// 경매 진행 중
AUCTION_IS_IN_PROGRESS,
// 경매 정상 마감
AUCTION_NORMAL_CLOSING,
// 경매 참여자 없음
AUCTION_NO_PARTICIPANTS
```
=> Feature/#12 경매글 생성 구현

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/AuctionPostService.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/dto/SearchAllAuctionPostDto.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/dto/SearchAuctionPostDto.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/vo/SearchAllAuctionPostResponseVo.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/vo/SearchAuctionResponseVo.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/presentation/AuctionPostController.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/cqrs/read/ReadAuctionPostRepository.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/mongotemplate/CustomReadAuctionPostRepository.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/mongotemplate/impl/CustomReadAuctionPostRepositoryImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/querydsl/AuctionImagesRepositoryCustom.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/querydsl/impl/AuctionImagesRepositoryCustomImpl.java
경매글 상세 조회 구현하였습니다.
간단한 로직이라 서비스 계층만 보시면 될 듯 합니다.
=> feat: 경매글 상세 조회 구현(#20)

src/test/java/com/skyhorsemanpower/BE_AuctionPost/BeAuctionPostApplicationTests.java, src/test/java/com/skyhorsemanpower/BE_AuctionPost/GenerateRandom.java
=> test: 더미 데이터 생성용 테스트 코드 작성

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/dto/AuctionPostDto.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/vo/ChangeAuctionPostStateRequestVo.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/domain/AuctionImages.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/presentation/AuctionPostController.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/mongotemplate/CustomReadAuctionPostRepository.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/mongotemplate/impl/CustomReadAuctionPostRepositoryImpl.java
=> Feature/#33 경매글 상태 변경 api 구현

src/test/java/com/skyhorsemanpower/BE_AuctionPost/BeAuctionPostApplicationTests.java
=> [DEPLOYMENT] 테스트 코드 주석 처리

src/test/java/com/skyhorsemanpower/BE_AuctionPost/BeAuctionPostApplicationTests.java
더미 데이터 생성용 테스트 코드를 배포합니다. 빌드시에 테스트가 동작하며 데이터를 생성합니다.
=> [DEPLOYMENT] 더미 데이터 생성용 테스트 코드 배포

src/test/java/com/skyhorsemanpower/BE_AuctionPost/BeAuctionPostApplicationTests.java
빌드 에러를 방지하기 위해 주석 처리한 테스트 코드를 배포합니다.
=> [DEPLOYMENT] 더미 데이터 생성용 테스트 코드 주석 처리

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/dto/AuctionPostDto.java
프론트 요청에 따라 경매글 리스트 조회에 state도 같이 반환합니다.
=> refactor: 경매글 리스트 조회 시, state도 같이 반환(#51)

src/main/java/com/skyhorsemanpower/BE_AuctionPost/presentation/InfluencerController.java
=> refactor: 인플루언서 검색 url 수정(#57)

src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/dto/SearchAuctionPostTitleDto.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/vo/SearchAuctionPostTitleAndInfluencerNameResponseVo.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/presentation/AuctionPostController.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/mongotemplate/CustomReadAuctionPostRepository.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/mongotemplate/impl/CustomReadAuctionPostRepositoryImpl.java
프론트 요청에 따라 키워드 입력하면 매칭되는 인플루언서 이름 1개, 경매글 제목 9개를 반환합니다.
=> refactor: 검색 페이지에 키워드 입력하면 인플루언서 이름 1개와 경매글 제목 9개를 반환합니다.(#50)

src/main/generated/com/skyhorsemanpower/BE_AuctionPost/domain/cqrs/command/QInfluencer.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/dto/SearchAllAuctionPostDto.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/presentation/AuctionPostController.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/mongotemplate/impl/CustomReadAuctionPostRepositoryImpl.java
검색하면 경매글 제목 또는 인플루언서 이름이 나온다.
데이터를 선택하면 관련된 경매글 리스트가 반환되도록 구현한다.
초기 검색으로 선택된 data를 가지고 경매글 검색을 influencerName과 title을 가지고 or 연산하여 리스트를 조회한다.
입력값이 없다면 전체 경매글 조회로 한다.
입력값 있는 경우
입력값 없는 경우
지금 endAuctionTime이 null로 나오는데 관련 리팩토링 전 데이터라서 그렇습니다.
=> feat: 입력값을 이용해 제목 또는 인플루언서 이름 매칭 경매글 리스트 조회 구현(#59)

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/status/AuctionLimitTimeEnum.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/status/ResponseStatus.java
#56 
한국 시간으로 입력하여 오후 10시 이전인 경우, 정상 생성
오후 10시 이후로 작성 시, 예외처리
=> refactor: 은행 점검 시간에 경매 제한(#56)

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/AuctionPostService.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/config/SwaggerConfig.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/config/kafkaconfig/KafkaConsumerCluster.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/config/kafkaconfig/KafkaConsumerConfig.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/dto/MainPagePostResponseDto.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/vo/MainPagePostResponseVo.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/presentation/AuctionPostController.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/repository/cqrs/read/ReadAuctionPostRepository.java
=> feat: swagger 긴급수정(#95)

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/AuctionPostService.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/data/vo/AuctionTotalDonationVo.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/kafka/KafkaConsumerCluster.java
- 기부금을 업데이트하는데 사용되는 VO의 이름을 변경했습니다.
- `UpdateTotalDonationUpdateVo` -> `AuctionTotalDonationVo`
=> refactor: 기부금 업데이트에 사용되는 VO 이름 변경

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java
경매글 생성 시, 메시지에 incrementUnit 누락 수정(#109)
=> refactor: 경매글 생성 시, 메시지에 incrementUnit 누락 수정(#109)

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/AuctionPostService.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/presentation/AuctionPostController.java
=> Feature/#116 경매 입장 버튼 누르면 경매 상태 조회

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java
=> refactor: conflict 누락된 부분 수정(#120)

src/main/java/com/skyhorsemanpower/BE_AuctionPost/kafka/KafkaProducerConfig.java
토픽 자동으로 삭제되도록 `ProducerConfig`파일 수정했습니다.
=> refactor: 토픽 자동 삭제 추가(#126)

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/kafka/KafkaProducerConfig.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/kafka/Topics.java
프로필 이미지를 포함하기 위해 member서비스로 메시지를 보내도록 수정했습니다.
토픽 명을 알아보기 편하게 수정했습니다.
토픽 설정을 수정했습니다
=> 채팅 서비스로 보내던 메시지를 멤버 서비스로 보내기/#125

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/InfluencerServiceImpl.java
인플루언서 등록 로직에 생년월일을 추가해 not null 에러를 고쳤습니다.
=> fix: 인플루언서 등록 로직에 생년월일 추가

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/kafka/dto/InitialAuctionDto.java
- `InitialAuctionDto`메시지에 `influencerUuid`를 추가했습니다.
=> refactor: influencerUuid 추가

src/main/java/com/skyhorsemanpower/BE_AuctionPost/application/impl/AuctionPostServiceImpl.java, src/main/java/com/skyhorsemanpower/BE_AuctionPost/kafka/dto/InitialAuctionDto.java
=> refactor: influencerName 추가
